FROM maven:3-jdk-11 AS build
COPY src /usr/src/app/src
COPY pom.xml /usr/src/app
RUN mvn -f /usr/src/app/pom.xml clean package -DskipTests=true

FROM openjdk:11-slim-buster
COPY --from=build /usr/src/app/target/pscextract-*.jar /usr/app/pscextract.jar
RUN mkdir -p /app/extract-repo && mkdir -p /app/resources
RUN chown -R daemon: /app
USER daemon
EXPOSE 8080
ENTRYPOINT ["sh", "-c", "exec java -jar /usr/app/pscextract.jar"]

